In [3]:
import numpy as np

In [5]:
# Example 1 Calculating Total Rvenue

prices =np.array([19.99,29.99,14.99,9.99,24.99])
print(prices)

quantities = np.array([10,5,8,12,3])
print(quantities)

revenue_per_product = prices *quantities
revenue_per_product

total_revenue = np.sum(revenue_per_product)
print(total_revenue)



[19.99 29.99 14.99  9.99 24.99]
[10  5  8 12  3]
664.62


In [10]:
#Example 2  analysing blog post stats

views = np.array([1000,500,800,1200,300,600])
print(views)

max_views =np.max(views)
print(max_views)

min_views =np.min(views)
print(min_views)

average_views =np.average(views)
print(average_views)

total_views =np.sum(views)
print(total_views)



[1000  500  800 1200  300  600]
1200
300
733.3333333333334
4400


In [14]:
# Example 3 Splitting order into batches

order_ids =np.array([1001,1002,1003,1004,1005,1006,1007,1008])
print(order_ids)

batches=np.split(order_ids,4)
print(batches)

for batch in batches:
    print(batch)



[1001 1002 1003 1004 1005 1006 1007 1008]
[array([1001, 1002]), array([1003, 1004]), array([1005, 1006]), array([1007, 1008])]
[1001 1002]
[1003 1004]
[1005 1006]
[1007 1008]


In [17]:
#Example 4 categorizing product rating 

ratings =np.array([4.5,3.5,4.2,2.9,4.8,2.9,4.1,4.4])
print(ratings)

positive_rating =ratings[ratings >4]
print(positive_rating)

negative_rating =ratings[ratings <4]
print(negative_rating)



[4.5 3.5 4.2 2.9 4.8 2.9 4.1 4.4]
[4.5 4.2 4.8 4.1 4.4]
[3.5 2.9 2.9]


In [20]:
#Example 5  calculaye average and total quantities sold

order_quantities =np.array([[5,3,2,7],[10,6,3,9]])
print(order_quantities)

total_product_per_oreder=np.sum(order_quantities,axis=1)
print(total_product_per_oreder)

average_quantities_sold =np.mean(order_quantities,axis=0)
print(average_quantities_sold)



[[ 5  3  2  7]
 [10  6  3  9]]
[17 28]
[7.5 4.5 2.5 8. ]


In [4]:
#Example 6 calculate average p[roduct rating and maximum rating per category

pro_reviews =np.array([[4.5,3.2,2.5,5.0],[4.3,3.8,1.0,4.8],[2.0,3.6,4.7,0.5]])
print(pro_reviews)

average_rating = np.mean(pro_reviews,axis=1)
print(average_rating)

max_rating =np.max(pro_reviews,axis=0)
print(max_rating)

[[4.5 3.2 2.5 5. ]
 [4.3 3.8 1.  4.8]
 [2.  3.6 4.7 0.5]]
[3.8   3.475 2.7  ]
[4.5 3.8 4.7 5. ]


In [10]:
# Pre building arrays witth 0s and 1s

print(np.arange(1,11))

print(np.arange(20,50,4))

print(np.zeros(3))
print(np.zeros((3,3)))

print(np.ones((2,4)))
print(np.ones(5))

[ 1  2  3  4  5  6  7  8  9 10]
[20 24 28 32 36 40 44 48]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [20]:
#random number generation
np.random.seed(35)
print(np.random.rand(2))

print(np.random.rand(5,5))


[0.45805495 0.30834961]
[[0.23148705 0.27742455 0.81723481 0.11134664 0.62643723]
 [0.27678789 0.68217467 0.67897078 0.79671742 0.04580216]
 [0.91259827 0.21381599 0.3036373  0.98906362 0.1858815 ]
 [0.98872484 0.75008423 0.22238605 0.14790391 0.51579028]
 [0.39425832 0.06988013 0.33822577 0.01103722 0.76752786]]


In [32]:
#np.random.seed(5)
print(np.random.randint(90,100,25))

[92 91 91 97 91 97 92 96 93 96 98 90 99 91 99 90 98 97 97 99 94 91 94 92
 91]


In [52]:
#Example 7 random array generation and opertsions on it

array1 = np.random.randint(1,100,20)
print("original array",array1)

result =np.where(array1 >50)
print("Resulted array ",array1[result])



original array [31 70 55 47 86 11 59 98 83 43 39 35 19 44 57 77  8 48 63 94]
Resulted array  [70 55 86 59 98 83 57 77 63 94]


In [53]:
arr1 =np.random.randint(1,100,10)
print(arr1)
arr2=np.random.randint(1,10,10)
print(arr2)
condition = arr1 > 5

result = np.where(condition,arr1,arr2)
result

[52 25 37 16 65 50  1  7 27  5]
[2 2 8 5 3 3 4 3 1 4]


array([52, 25, 37, 16, 65, 50,  4,  7, 27,  4])