In [34]:
# importing libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 


In [35]:
# imorting the dataset
dataset =pd.read_csv("D:/DBDA/Adavance Stats/pandas/Social_Network_Ads.csv")



In [36]:
#extract the feature variable from dataframe. It uses the .iloc method  to select all rows (denoted by :) and columns with indices 2 and 3 (python uses 0 bases index ,so these are 3
# 4 column: age and salary )... values converts the selected data into numpy array , which is a common format for feature variables in ml

X =dataset.iloc[:,[2,3]].values


In [ ]:
###############################Add gender to show the labels using Label Encoder##################################
# labelencoder will use 0 and 1 instaed of male and female
# import label encoder
from sklearn.preprocessing import LabelEncoder

# create label encoder object
encoder = LabelEncoder()

# get encoded featrures for the gender column

gender_encoded = encoder.fit_transform(dataset['Gender'].values.reshape(-1,1))

# add encoded features to the existing features set 

X=np.concatenate((X,gender_encoded.reshape(-1,1)),axis=1)
print(X)

In [ ]:
##############################################onehot encoding ###########################

# This method creates new binary column for each unique values in the gender column. For example, if the only values are "Male" and "Female" 
#you will get the two new columns: "Male" and "Female".
# Each row in the new column will have a value of 1 if the corresponding gender is presenst and 0 otherwise.

# Import one-hot encoder
from sklearn.preprocessing import OneHotEncoder

# Create one-hot encoder object
encoder = OneHotEncoder(sparse_output=False, drop='first')

# Get one-hot encoded features for gender column
gender_encoded = encoder.fit_transform(dataset['Gender'].values.reshape(-1,1))

# Add encoded features to the existing featuere set
X=np.concatenate((X,gender_encoded.reshape(-1,1)),axis=1)
print(X)


In [37]:
########################################## FREQUENCY based encoding #######################################################
# This method replace each unique value in the "Gender" columns with its frequency in the 
# entire dataset .Ex ,if there are 100 Male values and 200 Female values ,then Male will be 
# replaced with 0.33 abd Female will be replaced by 0.67

from collections import Counter

#get Gender frequencies

gender_counts = Counter(dataset['Gender'])
print(gender_counts)
#Define a function encode_gender values
def encode_gender(gender):
    return gender_counts[gender]/len(dataset)


# apply the encoding function to the gender column

dataset['Gender']= dataset['Gender'].apply(encode_gender)

#update the feature set wiuth encoded gender column
X = dataset.iloc[:,[1,2,3,]].values
print(X)


Counter({'Female': 204, 'Male': 196})
[[4.9e-01 1.9e+01 1.9e+04]
 [4.9e-01 3.5e+01 2.0e+04]
 [5.1e-01 2.6e+01 4.3e+04]
 ...
 [5.1e-01 5.0e+01 2.0e+04]
 [4.9e-01 3.6e+01 3.3e+04]
 [5.1e-01 4.9e+01 3.6e+04]]


In [38]:
#extracts the target variable (purchases) from the dataframe .It selects all rows and the last column(denoted by -1) of the dataframe and converts intp Numpy array.The
#target varibale typically contains the labels or outcomes you want to predict in a machine learing model

y =dataset.iloc[:,-1].values

In [39]:
# splitting the dataset into the training set(80%) and testing set(20%) 
# random state =0 sets a random seed to ensure reproducibilty. Setting this parameter to a specific values(eg .0) ensures that every time you run the code , 
#the same split will be generated .This is helpful for reproducibilty in Ml exp.

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [40]:
#feature scaling
# to ensure that all the features are on asimilar scale (eg age has a scale 1-100,but salary will be in thousands )

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [41]:
# the fit_transform method computes the mean ,standard deviation of each feature in the training set and then scales the features based on these stats.
#After scaling , the feature variable in X_train will have a mean 0 and SD of 1

X_train=sc.fit_transform(X_train)

#print(X_train)

In [42]:
#this line scales te features variables in testing set (X_test). however, it doesnot recompute the mean and SD : instead ,it uses the mean and Sd that were computed
# from the training set durung the fit_transform step . This ensures thatthe same scaling transformation is applied consistently to hboth the training and testing sets

X_test =sc.transform(X_test)



In [43]:
# training the naive bayes model on training set

from sklearn.naive_bayes import GaussianNB
classifier =GaussianNB()
classifier.fit(X_train,y_train)




GaussianNB()

In [44]:
#predicting the test set values/results

y_pred=classifier.predict(X_test)
print(y_pred)  #our predicted values
print(y_test) # actual values


[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 1]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [45]:
#after executing these lines, the classifier object will have learned the relationships
#between the features and target variables based on the GaussinNB model. You 
# how did we perform
# in this code snippet you are using sklearn cinfusion matrix and accuracy_score
##functions to evaluate the performance of ypour GaussianNB classifier on the test data


In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score
#ac =accuracy_score(y_test,y_pred) : This line calculates the accuracy of score of your classifier predictions Here how is works:

#y_test contains the actual target values (ground truth ) for the test set.
# y_pred contains the predicted target values made by GaussianNb classifier in the test set
#the accuracy_score  function compares y_test and y_pred , and it calculates the ratio  of correctly predicted instances to the total no. of instances

#This ratio is the accuracy of your classifier on the test data


In [48]:
ac =accuracy_score(y_test,y_pred)

#cm =confusion_matrix(y_test,y_pred): This line calculates matrix for your classifiers predictions. Here is what it does :
#y_test contains the actual target values (ground truth ) for the test set.
# y_pred contains the predicted target values made by GaussianNb classifier in the test set
# the confusion matrix function takes y_test and y_pred as input and computes matrix that shows the TP,TN,FP,FN values

cm =confusion_matrix(y_test,y_pred)


In [49]:
#ac : This variable contains the accuracy_score ,which quantifies the overall correctness of your classifiers predictions on the test data set
#cm : This variable contains the confusuion matrix which provides the detailed breakdown of how your classifiers predictions compare to actual truth values, allowing 
#you to assses

print(ac)
print(cm)

0.925
[[56  2]
 [ 4 18]]
